/*******************************************************************************
 * Copyright (c) 1999-2005 The Institute for Genomic Research (TIGR).
 * Copyright (c) 2005-2008, the Dana-Farber Cancer Institute (DFCI), 
 * J. Craig Venter Institute (JCVI) and the University of Washington.
 * All rights reserved.
 *******************************************************************************/
/*
 * SampleSelectionPanel.java
 * Added this new panel to provide the data centering option.
 *
 * Created on December 12, 2002, 4:56 PM
 * @author Raktim Sinha
 */

package org.tigr.microarray.mev.cluster.gui.impl.dialogs;

import java.awt.Color;
import java.awt.event.ActionListener;


/**
 * Added panel to PCA to allow users to center data 
 * by mean or median applicable to both samples or genes
 * @author  Raktim
 */
public class CenteringModePanel extends javax.swing.JPanel {

    boolean result = true;
    
    /** Creates new form SampleSelectionPanel */
    public CenteringModePanel() {
        this(Color.gray, Color.black, false, null);
    }
    
   /** Creates new form SampleSelectionPanel */
    public CenteringModePanel(Color background, Color foreground, boolean etchedTitleBorder, String borderTitle){
        initComponentsWithoutTheStupidForm();
        setBackground(background);
        setForeground(foreground);
        this.centerMedianButton.setBackground(background);
        this.centerMedianButton.setForeground(foreground);
        this.centerMeanButton.setBackground(background);
        this.centerMeanButton.setForeground(foreground);
        this.centerNoneButton.setBackground(background);
        this.centerNoneButton.setForeground(foreground);
        
        if(etchedTitleBorder)
        setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), borderTitle, 
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Dialog", 1, 12), Color.black));               
    }
    
    public void setButtonText(String medianButtonText, String meanButtonText, String noneButtonText){
        this.centerMedianButton.setText(medianButtonText);
        this.centerMeanButton.setText(meanButtonText);
        this.centerNoneButton.setText(noneButtonText);
        this.validate();
    }   
    
    public boolean isMedianSelected(){
        return this.centerMedianButton.isSelected();
    }
    
    public boolean isNoneSelected(){
        return this.centerNoneButton.isSelected();
    }
    
    public void setMedianSelected(boolean value){
        centerMedianButton.setSelected(value);
    }

    public void setMeanButtonActionListener(ActionListener listener){
        centerMeanButton.addActionListener(listener);
    }
    
    public void setMedianButtonActionListener(ActionListener listener){
        centerMedianButton.addActionListener(listener);
    }
    
    public void setNoneButtonActionListener(ActionListener listener){
    	centerNoneButton.addActionListener(listener);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        selectButtonGroup = new javax.swing.ButtonGroup();
        centerMedianButton = new javax.swing.JRadioButton();
        centerMeanButton = new javax.swing.JRadioButton();
        centerNoneButton = new javax.swing.JRadioButton();
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        centerMedianButton.setSelected(true);
        centerMedianButton.setText("Median");
        selectButtonGroup.add(centerMedianButton);
        centerMedianButton.setFocusPainted(false);
        centerMedianButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        add(centerMedianButton, gridBagConstraints1);
        
        centerMeanButton.setText("Mean");
        selectButtonGroup.add(centerMeanButton);
        centerMeanButton.setFocusPainted(false);
        centerMeanButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        add(centerMeanButton, gridBagConstraints1);
        
        //centerNoneButton.setSelected(true);
        centerNoneButton.setText("None");
        centerNoneButton.add(centerNoneButton);
        centerNoneButton.setFocusPainted(false);
        centerNoneButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 2;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        add(centerNoneButton, gridBagConstraints1);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup selectButtonGroup;
    private javax.swing.JRadioButton centerMedianButton;
    private javax.swing.JRadioButton centerMeanButton;
    private javax.swing.JRadioButton centerNoneButton;
    // End of variables declaration//GEN-END:variables

        
    private void initComponentsWithoutTheStupidForm() {
        selectButtonGroup = new javax.swing.ButtonGroup();
        centerMedianButton = new javax.swing.JRadioButton();
        centerMeanButton = new javax.swing.JRadioButton();
        centerNoneButton = new javax.swing.JRadioButton();;
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        centerMedianButton.setSelected(true);
        centerMedianButton.setText("Median");
        selectButtonGroup.add(centerMedianButton);
        centerMedianButton.setFocusPainted(false);
        centerMedianButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        add(centerMedianButton, gridBagConstraints1);
        
        centerMeanButton.setText("Mean");
        selectButtonGroup.add(centerMeanButton);
        centerMeanButton.setFocusPainted(false);
        centerMeanButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        add(centerMeanButton, gridBagConstraints1);
        
        //centerNoneButton.setSelected(true);
        centerNoneButton.setText("None");
        selectButtonGroup.add(centerNoneButton);
        centerNoneButton.setFocusPainted(false);
        centerNoneButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 2;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 1.0;
        add(centerNoneButton, gridBagConstraints1);
        
    }


}
