/*******************************************************************************
 * Copyright (c) 1999-2005 The Institute for Genomic Research (TIGR).
 * Copyright (c) 2005-2008, the Dana-Farber Cancer Institute (DFCI), 
 * J. Craig Venter Institute (JCVI) and the University of Washington.
 * All rights reserved.
 *******************************************************************************/
/*
 * CGHDisplayOrderChanger.java
 *
 * Created on March 24, 2003, 6:41 PM
 */

package org.tigr.microarray.mev.cgh.CGHGuiObj;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import org.tigr.microarray.mev.cluster.gui.IData;

/**
 *
 * @author  Adam Margolin
 * @author Raktim Sinha
 */

public class CGHSampleDeleter extends javax.swing.JDialog {
    private int deletedIndex = -1;

    //CGHMultipleArrayDataFcd fcd;
    private int result;

    /** Creates new form CGHDisplayOrderChanger */
    public CGHSampleDeleter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CGHSampleDeleter(IData data, java.awt.Frame parent, boolean modal){
        super(parent, modal);

        initComponents();

        listData.setModel(new DefaultListModel());

        int[] indicesOrder = data.getSamplesOrder();
        for(int i = 0; i < data.getFeaturesCount(); i++){
            ((DefaultListModel)listData.getModel()).addElement(data.getSampleName(indicesOrder[i] ));
        }

        setSize(400, 400);
    }

    /**
     * Shows the dialog.
     */
    public int showModal() {
        org.tigr.microarray.mev.cgh.CGHGuiObj.GuiUtil.GuiUtil.center(this);
        show();
        return result;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listData = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(listData);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel3.add(btnDelete);

        jPanel2.add(jPanel3);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jPanel4.add(btnOk);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel4.add(btnCancel);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Add your handling code here:
        result = JOptionPane.CANCEL_OPTION;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Add your handling code here:
        deletedIndex = listData.getSelectedIndex();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        result = JOptionPane.OK_OPTION;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed


    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        result = JOptionPane.CLOSED_OPTION;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /** Getter for property deletedIndex.
     * @return Value of property deletedIndex.
     */
    public int getDeletedIndex() {
        return deletedIndex;
    }

    /** Setter for property deletedIndex.
     * @param deletedIndex New value of property deletedIndex.
     */
    public void setDeletedIndex(int deletedIndex) {
        this.deletedIndex = deletedIndex;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JList listData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnCancel;
    // End of variables declaration//GEN-END:variables

}
